import tensorflow as tf

import numpy as np

## Agent that uses the monte carlo policy gradient algorithm
class PolicyGradientAgent():

    ## constructor
    def __init__(self, learning_rate = 0.001, discount_factor = 0.99, epsilon = 0.5, n_actions = 10, n_inputs = 10, n_layers = 2, layer_size = [16, 16]):
        self.policy = self.buildModel(n_actions = n_actions, n_inputs = n_inputs, n_layers = n_layers, layer_size=layer_size)
        self.optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
        self.policy.compile(optimizer=self.optimizer)
        self.learning_rate = learning_rate
        self.n_actions = n_actions
        self.n_inputs = n_inputs
        self.n_layers = n_layers
        self.layer_size = layer_size
        self.state_memory = []
        self.reward_memory = []
        self.action_memory = []
        self.discount_factor = discount_factor
        self.epsilon = epsilon

    ## build model function that builds a tensorflow keras sequential model with the parameters as specs
    def buildModel(self, n_actions=10, n_inputs=10, n_layers=2, layer_size=[16, 16]):
        model = tf.keras.Sequential([
            tf.keras.Input(shape=(n_inputs,))
        ])
        for i in range(n_layers):
            model.add(tf.keras.layers.Dense(layer_size[i], activation='relu'))
        model.add(tf.keras.layers.Dense(n_actions, activation='softmax'))
        return model
        
    ## chooses an action given an observation
    def choose_action(self, observation):

        ## get the probability output given the observation as input
        probs = self.policy.predict(observation)[0]

        ## return an epsilon greedy choice
        return self.epsilon_greedy_choice(probs)
    
    ## stores the memory of an observation, action and reward
    def store_transition(self, observation, action, reward):
        self.reward_memory.append(reward)
        self.action_memory.append(action)
        self.state_memory.append(observation)

    ## chooses with an epsilon greedy choice
    def epsilon_greedy_choice(self, probs):

        ## generate a random number between 0 and 1. If it is less than the epsilon value, then pick uniformly randomly from the choices
        if np.random.uniform() < self.epsilon:
            return np.random.choice(len(probs))
        
        ## otherwise pick from the probability distribution generated by the model
        else:
            return np.random.choice(len(probs), p=probs)

    ## set epsilon (for epsilon greedy choosing)
    def set_epsilon(self, epsilon):
        self.epsilon = epsilon

    ## learn function that updates the neural network given it's memory
    def learn(self):
        
        ## get the reward memory
        rewards = self.reward_memory 
        returns = [] ## discounted returns
        G = 0

        ## for each reward (starting from the last reward)
        ## set G to the reward + discount_factor * previous G
        ## then insert G into the beginning of the returns array
        for reward in reversed(rewards):
            G = reward + self.discount_factor * G
            returns.insert(0, G)
        returns = np.array(returns) ## convert to np.array

        ## whiten the returns with standardization
        returns = (returns - np.mean(returns))/(np.std(returns) + 1e-8)

        ## loop through the states, actions and returns
        for state, action, return_t in zip(self.state_memory, self.action_memory, returns):

            ## convert the state and return to a tensor
            state = tf.convert_to_tensor([np.array(state)], tf.float32)
            return_t = tf.convert_to_tensor(return_t, tf.float32)
            
            ## using gradient tape
            ## get the probabilites given the state
            ## clip the probabilites to be between (almost 0) and 1
            ## get the log of the probabilities of the taken action
            ## calculate the loss as the negative log probabiltity times the return
            with tf.GradientTape() as tape:
                probs = self.policy(state)
                probs = tf.clip_by_value(probs, 1e-10, 1.0)
                log_prob = tf.math.log(probs[0, action])
                loss = -log_prob * return_t # 

            ## get the gradients of the loss
            grads = tape.gradient(loss, self.policy.trainable_variables)

            ## normalize each gradient
            grads = [tf.clip_by_norm(grad, 1.0) for grad in grads]

            ## apply the gradients to the policy
            self.policy.optimizer.apply_gradients(zip(grads, self.policy.trainable_variables))

        # reset the memory
        self.state_memory = []
        self.reward_memory = []
        self.action_memory = []

    ## save the model
    def save_model(self, path):
        self.policy.save(path)
    
    ## load the model
    def load_model(self, path):
        self.policy.load_model(path)